import hashlib
import hmac
import json
import os
import secrets
import smtplib
import threading
import time
from contextlib import contextmanager
from datetime import datetime, timedelta, timezone
from email.message import EmailMessage
from functools import wraps
from pathlib import Path
from urllib.error import HTTPError, URLError
from urllib.parse import quote, urlparse
from urllib.request import Request, urlopen

import psycopg
from email_validator import EmailNotValidError, validate_email
from flask import Flask, abort, jsonify, redirect, render_template, request, send_from_directory, session, url_for
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from flask_wtf.csrf import CSRFError, CSRFProtect
from psycopg.rows import dict_row
from werkzeug.middleware.proxy_fix import ProxyFix
from werkzeug.security import check_password_hash, generate_password_hash


BASE_DIR = Path(__file__).resolve().parent
DATABASE_URL = os.environ.get("DATABASE_URL", "")
WHATSAPP_NUMBER = "5491161471426"
PUBLIC_ASSETS = {"index.html", "styles.css"}
MEMBERSHIP_PLANS = {
    "basic": {"name": "Basic", "price": 5000, "description": "Soporte remoto y prioridad estándar."},
    "intermedio": {"name": "Intermedio", "price": 9000, "description": "Soporte remoto y una visita mensual."},
    "premium": {"name": "Premium", "price": 15000, "description": "Atención prioritaria y dos visitas mensuales."},
}
ADMIN_SESSION_SECONDS = 2 * 60 * 60
PASSWORD_RESET_HOURS = 1
MEMBERSHIP_DAYS = 30

if not DATABASE_URL.startswith(("postgres://", "postgresql://")):
    raise RuntimeError("Define DATABASE_URL con la cadena de conexión PostgreSQL (postgresql://...).")

IS_PRODUCTION = bool(os.environ.get("RENDER")) or os.environ.get("APP_ENV") == "production"
if IS_PRODUCTION and not os.environ.get("SECRET_KEY"):
    # Una clave aleatoria invalida todas las sesiones en cada reinicio o entre workers.
    raise RuntimeError("Falta la variable de entorno obligatoria SECRET_KEY.")

app = Flask(__name__)
app.config.update(
    SECRET_KEY=os.environ.get("SECRET_KEY", os.urandom(32)),
    PREFERRED_URL_SCHEME="https",
    SESSION_COOKIE_HTTPONLY=True,
    SESSION_COOKIE_SAMESITE="Lax",
    SESSION_COOKIE_SECURE=IS_PRODUCTION,
    PERMANENT_SESSION_LIFETIME=timedelta(days=14),
    WTF_CSRF_TIME_LIMIT=None,  # El token vive lo mismo que la sesión.
    WTF_CSRF_SSL_STRICT=False,  # No exigir Referer: hay navegadores y extensiones que lo quitan.
)
app.wsgi_app = ProxyFix(app.wsgi_app, x_for=1, x_proto=1, x_host=1)
csrf = CSRFProtect(app)
# El almacenamiento en memoria es por proceso; con varios workers usa RATELIMIT_STORAGE_URI (Redis).
limiter = Limiter(
    get_remote_address,
    app=app,
    storage_uri=os.environ.get("RATELIMIT_STORAGE_URI", "memory://"),
)
database_initialized = False
database_init_lock = threading.Lock()
DATABASE_ERRORS = (psycopg.Error,)
INTEGRITY_ERRORS = (psycopg.IntegrityError,)


@contextmanager
def get_db():
    connection = psycopg.connect(DATABASE_URL, row_factory=dict_row)
    try:
        yield connection
        connection.commit()
    except Exception:
        connection.rollback()
        raise
    finally:
        connection.close()


def init_db():
    """Crea y actualiza el esquema de PostgreSQL."""
    with get_db() as connection:
        connection.execute(
            """
            CREATE TABLE IF NOT EXISTS users (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username TEXT NOT NULL UNIQUE,
                created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                email TEXT,
                password_hash TEXT,
                email_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
                confirmation_token TEXT,
                confirmation_expires TIMESTAMPTZ,
                membership_plan TEXT,
                membership_status TEXT NOT NULL DEFAULT 'inactive',
                membership_started_at TIMESTAMPTZ,
                membership_expires_at TIMESTAMPTZ,
                reset_token_hash TEXT,
                reset_expires TIMESTAMPTZ
            )
            """
        )
        connection.execute(
            """
            CREATE TABLE IF NOT EXISTS service_records (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id BIGINT NOT NULL REFERENCES users(id),
                job TEXT NOT NULL,
                payment DOUBLE PRECISION NOT NULL DEFAULT 0,
                service_history TEXT NOT NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
            """
        )
        connection.execute(
            """
            CREATE TABLE IF NOT EXISTS membership_payments (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                payment_reference TEXT NOT NULL UNIQUE,
                user_id BIGINT NOT NULL REFERENCES users(id),
                plan TEXT NOT NULL,
                amount DOUBLE PRECISION NOT NULL,
                preference_id TEXT,
                mp_payment_id TEXT UNIQUE,
                status TEXT NOT NULL DEFAULT 'pending',
                created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                paid_at TIMESTAMPTZ
            )
            """
        )
        migrations = {
            "email": "TEXT",
            "password_hash": "TEXT",
            "email_confirmed": "BOOLEAN NOT NULL DEFAULT FALSE",
            "confirmation_token": "TEXT",
            "confirmation_expires": "TIMESTAMPTZ",
            "membership_plan": "TEXT",
            "membership_status": "TEXT NOT NULL DEFAULT 'inactive'",
            "membership_started_at": "TIMESTAMPTZ",
            "membership_expires_at": "TIMESTAMPTZ",
            "reset_token_hash": "TEXT",
            "reset_expires": "TIMESTAMPTZ",
        }
        for column, definition in migrations.items():
            connection.execute(f"ALTER TABLE users ADD COLUMN IF NOT EXISTS {column} {definition}")
        # Membresías activadas antes de que existiera el vencimiento: cuentan desde su inicio.
        connection.execute(
            "UPDATE users SET membership_expires_at = membership_started_at + make_interval(days => %s) "
            "WHERE membership_status = 'active' AND membership_expires_at IS NULL "
            "AND membership_started_at IS NOT NULL",
            (MEMBERSHIP_DAYS,),
        )
        connection.execute(
            "CREATE UNIQUE INDEX IF NOT EXISTS users_email_unique "
            "ON users(LOWER(email)) WHERE email IS NOT NULL"
        )
        # El nombre de usuario también es único sin distinguir mayúsculas. Si ya hubiera
        # duplicados no se crea el índice (fallaría el arranque) y se avisa en el log.
        duplicated = connection.execute(
            "SELECT LOWER(username) AS username FROM users GROUP BY LOWER(username) HAVING COUNT(*) > 1"
        ).fetchall()
        if duplicated:
            app.logger.error(
                "Hay nombres de usuario repetidos (sin distinguir mayúsculas): %s. "
                "Corrígelos para activar el índice único.",
                ", ".join(row["username"] for row in duplicated),
            )
        else:
            connection.execute(
                "CREATE UNIQUE INDEX IF NOT EXISTS users_username_unique ON users(LOWER(username))"
            )
        connection.execute(
            "CREATE INDEX IF NOT EXISTS membership_payments_user_id_idx "
            "ON membership_payments(user_id)"
        )
        # Supabase expone el esquema public por su API REST con la clave anon (pública).
        # Con RLS activo y sin políticas, esa API no puede leer ni escribir estas tablas;
        # la aplicación no se ve afectada porque se conecta con el rol propietario.
        for table in ("users", "service_records", "membership_payments"):
            connection.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")


def parse_timestamp(value):
    """Devuelve un datetime con zona horaria a partir de un datetime o de un texto ISO."""
    if isinstance(value, str):
        value = datetime.fromisoformat(value)
    if value.tzinfo is None:
        value = value.replace(tzinfo=timezone.utc)
    return value


def membership_state(user):
    """'active', 'expired' o 'inactive' según el estado guardado y la fecha de vencimiento."""
    if user["membership_status"] != "active":
        return "inactive"
    expires = user.get("membership_expires_at")
    if expires and parse_timestamp(expires) < datetime.now(timezone.utc):
        return "expired"
    return "active"


def user_required(view):
    @wraps(view)
    def wrapped(*args, **kwargs):
        if not session.get("user_id"):
            return redirect(url_for("user_login", next=request.path))
        return view(*args, **kwargs)

    return wrapped


def admin_session_active():
    return bool(session.get("admin_authenticated")) and (
        time.time() - session.get("admin_at", 0) < ADMIN_SESSION_SECONDS
    )


def admin_required(view):
    @wraps(view)
    def wrapped(*args, **kwargs):
        if not admin_session_active():
            session.pop("admin_authenticated", None)
            return redirect(url_for("admin_login"))
        return view(*args, **kwargs)

    return wrapped


def safe_next_url(value, default):
    """Solo admite rutas relativas del propio sitio para evitar redirecciones abiertas."""
    if not value or not value.startswith("/") or value.startswith("//") or "\\" in value or "%5c" in value.lower():
        return default
    if any(ord(char) < 32 for char in value):
        return default
    parsed = urlparse(value)
    if parsed.scheme or parsed.netloc:
        return default
    return value


def hash_token(token):
    return hashlib.sha256(token.encode("utf-8")).hexdigest()


@app.errorhandler(CSRFError)
def csrf_error(error):
    return render_template(
        "error.html",
        title="La página caducó",
        message="No pudimos verificar el formulario. Vuelve atrás, recarga la página e inténtalo de nuevo.",
    ), 400


@app.errorhandler(429)
def too_many_requests(error):
    return render_template(
        "error.html",
        title="Demasiados intentos",
        message="Hiciste demasiados intentos en poco tiempo. Espera unos minutos y vuelve a probar.",
    ), 429


@app.before_request
def prepare_database():
    global database_initialized
    if database_initialized:
        return None
    try:
        with database_init_lock:
            if not database_initialized:
                init_db()
                database_initialized = True
    except DATABASE_ERRORS:
        app.logger.exception("No se pudo inicializar la base de datos")
        if request.path == "/usuarios/registro" and request.method == "POST":
            return render_template(
                "user_register.html",
                error="La base de datos no está disponible. Intenta nuevamente en unos minutos.",
            ), 503
        raise


@app.get("/")
def home():
    return send_from_directory(BASE_DIR, "index.html")


@app.get("/healthz")
def healthz():
    return jsonify(status="ok")


@app.get("/<path:filename>")
def assets(filename):
    if filename not in PUBLIC_ASSETS:
        abort(404)
    return send_from_directory(BASE_DIR, filename)


@app.post("/contacto")
@csrf.exempt  # Se envía desde la landing estática (otro origen) y solo redirige a WhatsApp.
@limiter.limit("10 per hour")
def contacto():
    nombre = request.form.get("nombre", "").strip()
    email = request.form.get("email", "").strip()
    telefono = request.form.get("telefono", "").strip()
    mensaje = request.form.get("mensaje", "").strip()
    if not nombre or not email or not mensaje:
        return redirect(url_for("home") + "#contacto"), 400

    texto = (
        "Hola, me gustaría contactarme con Up Time.\n\n"
        f"Nombre: {nombre}\n"
        f"Email: {email}\n"
        f"Teléfono: {telefono}\n\n"
        f"Mensaje: {mensaje}"
    )
    return redirect(
        f"https://wa.me/{WHATSAPP_NUMBER}?text={quote(texto)}",
        code=303,
    )


def send_email(to, subject, body):
    smtp_host = os.environ.get("SMTP_HOST")
    smtp_user = os.environ.get("SMTP_USER")
    smtp_password = os.environ.get("SMTP_PASSWORD")
    if not all((smtp_host, smtp_user, smtp_password)):
        return False

    message = EmailMessage()
    message["Subject"] = subject
    message["From"] = os.environ.get("SMTP_FROM", smtp_user)
    message["To"] = to
    message.set_content(body)
    try:
        with smtplib.SMTP(smtp_host, int(os.environ.get("SMTP_PORT", "587")), timeout=15) as server:
            if os.environ.get("SMTP_USE_TLS", "true").lower() in {"1", "true", "yes"}:
                server.starttls()
            server.login(smtp_user, smtp_password)
            server.send_message(message)
    except (OSError, smtplib.SMTPException, ValueError) as error:
        app.logger.warning("No se pudo enviar el email '%s': %s", subject, error)
        return False
    return True


def send_confirmation_email(email, confirmation_url):
    return send_email(
        email,
        "Confirma tu email - Up Time",
        "Confirma tu cuenta de Up Time abriendo este enlace:\n\n"
        f"{confirmation_url}\n\nEste enlace vence en 24 horas.",
    )


def send_password_reset_email(email, reset_url):
    return send_email(
        email,
        "Restablece tu contraseña - Up Time",
        "Recibimos un pedido para restablecer tu contraseña de Up Time. "
        "Si fuiste tú, abre este enlace:\n\n"
        f"{reset_url}\n\nEl enlace vence en {PASSWORD_RESET_HOURS} hora. "
        "Si no lo pediste, ignora este mensaje.",
    )


def mercado_pago_request(path, method="GET", payload=None):
    access_token = os.environ.get("MERCADOPAGO_ACCESS_TOKEN")
    if not access_token:
        raise RuntimeError("Mercado Pago no está configurado.")
    data = json.dumps(payload).encode("utf-8") if payload is not None else None
    request_data = Request(
        f"https://api.mercadopago.com{path}",
        data=data,
        method=method,
        headers={
            "Authorization": f"Bearer {access_token}",
            "Content-Type": "application/json",
            "Accept": "application/json",
        },
    )
    try:
        with urlopen(request_data, timeout=15) as response:
            return json.loads(response.read().decode("utf-8"))
    except (HTTPError, URLError, TimeoutError, ValueError) as error:
        app.logger.warning("Error al comunicarse con Mercado Pago: %s", error)
        raise RuntimeError("No se pudo iniciar o verificar el pago. Intenta nuevamente.") from error


REFUND_STATUSES = {"refunded", "charged_back", "cancelled"}


def payment_matches_order(payment, order):
    try:
        paid_amount = float(payment.get("transaction_amount"))
    except (TypeError, ValueError):
        return False
    return payment.get("currency_id") == "ARS" and abs(paid_amount - float(order["amount"])) < 0.01


def apply_mercado_pago_payment(payment_id, expected_user_id=None):
    """Sincroniza un pago de Mercado Pago con su pedido. Devuelve True si el pedido está aprobado."""
    payment_id = str(payment_id)
    if not payment_id.isdigit():
        return False
    payment = mercado_pago_request(f"/v1/payments/{payment_id}")
    reference = payment.get("external_reference")
    if not reference:
        return False
    status = payment.get("status", "pending")
    now = datetime.now(timezone.utc)
    with get_db() as connection:
        order = connection.execute(
            "SELECT * FROM membership_payments WHERE payment_reference = %s FOR UPDATE", (reference,)
        ).fetchone()
        if not order:
            return False
        if expected_user_id is not None and order["user_id"] != expected_user_id:
            return False

        if status == "approved":
            if order["status"] == "approved":
                return True  # Idempotente: el webhook y el regreso del usuario pueden llegar ambos.
            if not payment_matches_order(payment, order):
                app.logger.error(
                    "El pago %s no coincide con el pedido %s (monto o moneda distintos).",
                    payment_id, order["id"],
                )
                return False
            connection.execute(
                "UPDATE membership_payments SET mp_payment_id = %s, status = 'approved', paid_at = %s WHERE id = %s",
                (payment_id, now, order["id"]),
            )
            connection.execute(
                "UPDATE users SET membership_plan = %s, membership_status = 'active', "
                "membership_started_at = %s, "
                "membership_expires_at = GREATEST(COALESCE(membership_expires_at, %s), %s) + make_interval(days => %s) "
                "WHERE id = %s",
                (order["plan"], now, now, now, MEMBERSHIP_DAYS, order["user_id"]),
            )
            return True

        if order["status"] == "approved":
            # Un pago tardío o rechazado no debe pisar un pedido aprobado; solo un
            # reembolso o contracargo del mismo pago desactiva la membresía.
            if status in REFUND_STATUSES and order["mp_payment_id"] == payment_id:
                connection.execute(
                    "UPDATE membership_payments SET status = %s WHERE id = %s", (status, order["id"])
                )
                connection.execute(
                    "UPDATE users SET membership_status = 'inactive' WHERE id = %s AND membership_plan = %s",
                    (order["user_id"], order["plan"]),
                )
            return False

        connection.execute(
            "UPDATE membership_payments SET mp_payment_id = %s, status = %s WHERE id = %s",
            (payment_id, status, order["id"]),
        )
    return False


def verify_mercado_pago_signature(data_id):
    """Valida la cabecera x-signature de los webhooks (HMAC-SHA256 con la clave secreta de MP)."""
    secret = os.environ.get("MERCADOPAGO_WEBHOOK_SECRET")
    if not secret:
        if IS_PRODUCTION:
            app.logger.error("MERCADOPAGO_WEBHOOK_SECRET no está configurada: se rechaza el webhook.")
            return False
        app.logger.warning("MERCADOPAGO_WEBHOOK_SECRET no está configurada: no se verifica la firma.")
        return True
    parts = {}
    for item in request.headers.get("x-signature", "").split(","):
        key, _, value = item.strip().partition("=")
        parts[key] = value
    timestamp, received = parts.get("ts"), parts.get("v1")
    if not timestamp or not received:
        return False
    manifest = ""
    if data_id:
        manifest += f"id:{data_id.lower()};"
    request_id = request.headers.get("x-request-id")
    if request_id:
        manifest += f"request-id:{request_id};"
    manifest += f"ts:{timestamp};"
    expected = hmac.new(secret.encode("utf-8"), manifest.encode("utf-8"), hashlib.sha256).hexdigest()
    return hmac.compare_digest(expected, received)


@app.get("/usuarios/registro")
def user_register():
    if session.get("user_id"):
        return redirect(url_for("user_dashboard"))
    return render_template("user_register.html")


@app.post("/usuarios/registro")
@limiter.limit("10 per hour")
def user_register_submit():
    username = request.form.get("username", "").strip()
    raw_email = request.form.get("email", "").strip()
    password = request.form.get("password", "")
    password_confirmation = request.form.get("password_confirmation", "")
    try:
        email = validate_email(raw_email, check_deliverability=False).normalized.lower()
    except EmailNotValidError:
        email = ""
    if (
        not username or len(username) > 100 or not email
        or not 8 <= len(password) <= 128 or password != password_confirmation
    ):
        return render_template(
            "user_register.html",
            error="Completa los datos y usa una contraseña de al menos 8 caracteres.",
        ), 400

    token = secrets.token_urlsafe(32)
    expires = datetime.now(timezone.utc) + timedelta(hours=24)
    try:
        with get_db() as connection:
            existing_email = connection.execute(
                "SELECT id FROM users WHERE lower(email) = %s", (email,)
            ).fetchone()
            if existing_email:
                return render_template("user_register.html", error="Ese email ya está registrado."), 409
            existing_username = connection.execute(
                "SELECT id FROM users WHERE lower(username) = %s", (username.lower(),)
            ).fetchone()
            if existing_username:
                return render_template("user_register.html", error="Ese nombre de usuario ya está registrado."), 409
            connection.execute(
                """
                INSERT INTO users (username, email, password_hash, email_confirmed,
                    confirmation_token, confirmation_expires)
                VALUES (%s, %s, %s, FALSE, %s, %s)
                """,
                (username, email, generate_password_hash(password), token, expires.isoformat()),
            )
    except INTEGRITY_ERRORS:
        return render_template("user_register.html", error="El usuario o email ya está registrado."), 409
    except DATABASE_ERRORS:
        app.logger.exception("No se pudo guardar el nuevo usuario")
        return render_template(
            "user_register.html",
            error="No se pudo crear la cuenta en este momento. Intenta nuevamente.",
        ), 503
    except Exception:
        app.logger.exception("Error inesperado durante el registro")
        return render_template(
            "user_register.html",
            error="No se pudo crear la cuenta en este momento. Intenta nuevamente.",
        ), 503

    confirmation_url = url_for("confirm_email", token=token, _external=True)
    email_sent = send_confirmation_email(email, confirmation_url)
    return render_template(
        "registration_complete.html",
        email=email,
        email_sent=email_sent,
    )


@app.post("/usuarios/reenviar-confirmacion")
@limiter.limit("5 per hour")
def resend_confirmation_email():
    try:
        email = validate_email(
            request.form.get("email", "").strip(), check_deliverability=False
        ).normalized.lower()
    except EmailNotValidError:
        email = ""

    if email:
        token = secrets.token_urlsafe(32)
        expires = (datetime.now(timezone.utc) + timedelta(hours=24)).isoformat()
        with get_db() as connection:
            user = connection.execute(
                "SELECT id FROM users WHERE lower(email) = %s AND email_confirmed = FALSE", (email,)
            ).fetchone()
            if user:
                connection.execute(
                    "UPDATE users SET confirmation_token = %s, confirmation_expires = %s WHERE id = %s",
                    (token, expires, user["id"]),
                )
                confirmation_url = url_for("confirm_email", token=token, _external=True)
                send_confirmation_email(email, confirmation_url)
    return render_template("registration_complete.html", email=email or "esa dirección", email_sent=True)


@app.get("/usuarios/confirmar-email/<token>")
def confirm_email(token):
    with get_db() as connection:
        user = connection.execute(
            "SELECT id, confirmation_expires FROM users WHERE confirmation_token = %s",
            (token,),
        ).fetchone()
        if not user:
            return render_template("confirmation_result.html", error="El enlace no es valido."), 404
        expires = parse_timestamp(user["confirmation_expires"])
        if expires < datetime.now(timezone.utc):
            return render_template("confirmation_result.html", error="El enlace ya vencio."), 400
        connection.execute(
            "UPDATE users SET email_confirmed = TRUE, confirmation_token = NULL, confirmation_expires = NULL WHERE id = %s",
            (user["id"],),
        )
    return render_template("confirmation_result.html", confirmed=True)


@app.get("/usuarios/login")
def user_login():
    if session.get("user_id"):
        return redirect(url_for("user_dashboard"))
    return render_template("user_login.html")


@app.post("/usuarios/login")
@limiter.limit("10 per minute;50 per hour")
def user_login_submit():
    email = request.form.get("email", "").strip().lower()
    password = request.form.get("password", "")
    with get_db() as connection:
        user = connection.execute(
            "SELECT id, password_hash, email_confirmed FROM users WHERE lower(email) = %s",
            (email,),
        ).fetchone()
    if not user or not user["password_hash"] or not check_password_hash(user["password_hash"], password):
        return render_template("user_login.html", error="Email o contraseña incorrectos."), 401
    if not user["email_confirmed"]:
        return render_template("user_login.html", error="Confirma tu email antes de ingresar."), 403
    session.clear()
    session.permanent = True
    session["user_id"] = user["id"]
    return redirect(safe_next_url(request.form.get("next", ""), url_for("user_dashboard")))


@app.get("/usuarios/recuperar")
def password_forgot():
    return render_template("user_forgot.html")


@app.post("/usuarios/recuperar")
@limiter.limit("5 per hour")
def password_forgot_submit():
    try:
        email = validate_email(
            request.form.get("email", "").strip(), check_deliverability=False
        ).normalized.lower()
    except EmailNotValidError:
        email = ""

    token = None
    if email:
        token = secrets.token_urlsafe(32)
        expires = datetime.now(timezone.utc) + timedelta(hours=PASSWORD_RESET_HOURS)
        with get_db() as connection:
            user = connection.execute(
                "SELECT id FROM users WHERE lower(email) = %s AND email_confirmed = TRUE", (email,)
            ).fetchone()
            if user:
                connection.execute(
                    "UPDATE users SET reset_token_hash = %s, reset_expires = %s WHERE id = %s",
                    (hash_token(token), expires, user["id"]),
                )
        if user:
            send_password_reset_email(email, url_for("password_reset", token=token, _external=True))
    # Misma respuesta exista o no la cuenta, para no revelar qué emails están registrados.
    return render_template("user_forgot.html", sent=True)


def find_user_by_reset_token(connection, token):
    user = connection.execute(
        "SELECT id, reset_expires FROM users WHERE reset_token_hash = %s", (hash_token(token),)
    ).fetchone()
    if user and user["reset_expires"] and parse_timestamp(user["reset_expires"]) > datetime.now(timezone.utc):
        return user
    return None


@app.route("/usuarios/restablecer/<token>", methods=["GET", "POST"])
@limiter.limit("10 per hour", methods=["POST"])
def password_reset(token):
    error = None
    with get_db() as connection:
        user = find_user_by_reset_token(connection, token)
        if not user:
            return render_template(
                "user_reset.html",
                invalid=True,
            ), 400
        if request.method == "POST":
            password = request.form.get("password", "")
            if not 8 <= len(password) <= 128 or password != request.form.get("password_confirmation", ""):
                error = "Usa una contraseña de al menos 8 caracteres y repítela igual."
            else:
                connection.execute(
                    "UPDATE users SET password_hash = %s, reset_token_hash = NULL, reset_expires = NULL WHERE id = %s",
                    (generate_password_hash(password), user["id"]),
                )
                return render_template("user_login.html", notice="Contraseña actualizada. Ya puedes ingresar.")
    return render_template("user_reset.html", error=error), (400 if error else 200)


@app.post("/usuarios/logout")
@user_required
def user_logout():
    session.clear()
    return redirect(url_for("user_login"))


@app.get("/usuarios")
@user_required
def user_dashboard():
    with get_db() as connection:
        user = connection.execute(
            "SELECT * FROM users WHERE id = %s", (session["user_id"],)
        ).fetchone()
        records = connection.execute(
            "SELECT * FROM service_records WHERE user_id = %s ORDER BY created_at DESC, id DESC",
            (session["user_id"],),
        ).fetchall()
    return render_template(
        "user_dashboard.html", user=user, records=records, membership_state=membership_state(user)
    )


@app.post("/usuarios/servicios/repetir/<int:record_id>")
@user_required
def repeat_service(record_id):
    with get_db() as connection:
        record = connection.execute(
            "SELECT job FROM service_records WHERE id = %s AND user_id = %s",
            (record_id, session["user_id"]),
        ).fetchone()
    if not record:
        return redirect(url_for("user_dashboard"))
    texto = f"Hola, quiero volver a solicitar el servicio: {record['job']}"
    return redirect(f"https://wa.me/{WHATSAPP_NUMBER}?text={quote(texto)}", code=303)


@app.get("/membresias")
def memberships():
    return render_template("memberships.html", plans=MEMBERSHIP_PLANS)


@app.post("/membresias/seleccionar")
def select_membership():
    plan = request.form.get("plan", "")
    if plan not in MEMBERSHIP_PLANS:
        return redirect(url_for("memberships"))
    if not session.get("user_id"):
        return redirect(url_for("user_login", next=url_for("memberships")))
    return render_template("membership_checkout.html", plan=MEMBERSHIP_PLANS[plan], plan_key=plan)


@app.post("/membresias/confirmar")
@user_required
def confirm_membership():
    plan = request.form.get("plan", "")
    if plan not in MEMBERSHIP_PLANS:
        return redirect(url_for("memberships"))
    plan_data = MEMBERSHIP_PLANS[plan]
    if not os.environ.get("MERCADOPAGO_ACCESS_TOKEN"):
        return render_template(
            "membership_checkout.html",
            plan=plan_data,
            plan_key=plan,
            error="El medio de pago aún no está configurado. Intenta nuevamente más tarde.",
        ), 503
    payment_reference = secrets.token_urlsafe(24)
    with get_db() as connection:
        user = connection.execute(
            "SELECT username, email FROM users WHERE id = %s", (session["user_id"],)
        ).fetchone()
        connection.execute(
            "INSERT INTO membership_payments (payment_reference, user_id, plan, amount) VALUES (%s, %s, %s, %s)",
            (payment_reference, session["user_id"], plan, plan_data["price"]),
        )
    try:
        preference = mercado_pago_request(
            "/checkout/preferences",
            method="POST",
            payload={
                "items": [{
                    "id": f"membership-{plan}",
                    "title": f"Membresía Up Time - {plan_data['name']}",
                    "quantity": 1,
                    "currency_id": "ARS",
                    "unit_price": plan_data["price"],
                }],
                "payer": {"name": user["username"], "email": user["email"]},
                "external_reference": payment_reference,
                "back_urls": {
                    "success": url_for("membership_payment_result", _external=True),
                    "failure": url_for("membership_payment_result", _external=True),
                    "pending": url_for("membership_payment_result", _external=True),
                },
                "notification_url": url_for("mercado_pago_webhook", _external=True),
            },
        )
    except RuntimeError as error:
        return render_template("membership_checkout.html", plan=plan_data, plan_key=plan, error=str(error)), 503

    checkout_url = preference.get(
        "sandbox_init_point" if os.environ.get("MERCADOPAGO_SANDBOX", "").lower() in {"1", "true", "yes"} else "init_point"
    )
    if not checkout_url:
        app.logger.error("Mercado Pago no devolvió una URL de checkout: %s", preference)
        return render_template("membership_checkout.html", plan=plan_data, plan_key=plan, error="No se pudo iniciar el pago."), 503
    with get_db() as connection:
        connection.execute(
            "UPDATE membership_payments SET preference_id = %s WHERE payment_reference = %s",
            (preference.get("id"), payment_reference),
        )
    return redirect(checkout_url, code=303)


@app.post("/pagos/mercado-pago/webhook")
@csrf.exempt  # Lo llama Mercado Pago; se autentica con la firma x-signature.
def mercado_pago_webhook():
    notification = request.get_json(silent=True)
    if not isinstance(notification, dict):
        notification = {}
    data = notification.get("data")
    body_id = data.get("id") if isinstance(data, dict) else None
    payment_id = body_id or request.args.get("data.id") or request.args.get("id")
    signed_id = request.args.get("data.id") or (str(body_id) if body_id else "")
    if not verify_mercado_pago_signature(signed_id):
        return "", 401
    notification_type = notification.get("type") or request.args.get("type") or request.args.get("topic")
    if payment_id and notification_type in {"payment", None}:
        try:
            apply_mercado_pago_payment(payment_id)
        except RuntimeError:
            # Mercado Pago reintentará el webhook si respondemos con error.
            return "", 500
    return "", 200


@app.get("/membresias/pago/resultado")
@user_required
def membership_payment_result():
    payment_id = request.args.get("payment_id") or request.args.get("collection_id")
    approved = False
    if payment_id:
        try:
            approved = apply_mercado_pago_payment(payment_id, expected_user_id=session["user_id"])
        except RuntimeError:
            pass
    return render_template("membership_pending.html", approved=approved)


@app.get("/gestion-privada")
def admin_login():
    if admin_session_active():
        return redirect(url_for("admin_dashboard"))
    return render_template("admin_login.html")


@app.post("/gestion-privada/login")
@limiter.limit("5 per minute;30 per hour")
def admin_login_submit():
    configured_username = os.environ.get("ADMIN_USERNAME")
    configured_password = os.environ.get("ADMIN_PASSWORD")
    username = request.form.get("username", "")
    password = request.form.get("password", "")

    valid_credentials = (
        configured_username
        and configured_password
        and hmac.compare_digest(username.encode("utf-8"), configured_username.encode("utf-8"))
        and hmac.compare_digest(password.encode("utf-8"), configured_password.encode("utf-8"))
    )
    if not valid_credentials:
        return render_template("admin_login.html", error="Credenciales invalidas"), 401

    session.clear()
    session["admin_authenticated"] = True
    session["admin_at"] = time.time()
    return redirect(url_for("admin_dashboard"))


@app.post("/gestion-privada/logout")
@admin_required
def admin_logout():
    session.clear()
    return redirect(url_for("admin_login"))


def load_admin_data():
    with get_db() as connection:
        users = connection.execute(
            "SELECT id, username, created_at FROM users ORDER BY username"
        ).fetchall()
        records = connection.execute(
            """
            SELECT service_records.*, users.username
            FROM service_records
            JOIN users ON users.id = service_records.user_id
            ORDER BY service_records.created_at DESC, service_records.id DESC
            """
        ).fetchall()
    return {"users": users, "records": records}


@app.route("/gestion-privada/panel", methods=["GET", "POST"])
@admin_required
def admin_dashboard():
    if request.method == "POST":
        username = request.form.get("username", "").strip()
        job = request.form.get("job", "").strip()
        service_history = request.form.get("service_history", "").strip()
        payment_text = request.form.get("payment", "0").strip().replace(",", ".")

        try:
            payment = float(payment_text)
        except ValueError:
            payment = -1

        if not username or not job or not service_history or payment < 0:
            return render_template(
                "admin_dashboard.html",
                **load_admin_data(),
                error="Completa todos los campos y usa un pago valido.",
            ), 400

        with get_db() as connection:
            find_user = "SELECT id FROM users WHERE LOWER(username) = LOWER(%s)"
            user = connection.execute(find_user, (username,)).fetchone()
            if not user:
                connection.execute(
                    "INSERT INTO users (username) VALUES (%s) ON CONFLICT DO NOTHING", (username,)
                )
                user = connection.execute(find_user, (username,)).fetchone()
            connection.execute(
                """
                INSERT INTO service_records (user_id, job, payment, service_history)
                VALUES (%s, %s, %s, %s)
                """,
                (user["id"], job, payment, service_history),
            )
        return redirect(url_for("admin_dashboard"))

    return render_template("admin_dashboard.html", **load_admin_data())


if __name__ == "__main__":
    app.run(
        debug=os.environ.get("FLASK_DEBUG") == "1",
        host="0.0.0.0",
        port=int(os.environ.get("PORT", "5000")),
    )
