"""baseline esquema actual

Transcribe el esquema que hoy crea init_db() en app.py, al 2026-09-29.
No reemplaza a init_db(): la app sigue arrancando igual que siempre. Esta
migracion sirve como punto de partida documentado, listo para el dia que
se decida cortar de verdad a Alembic (ver migrations/README.md del
proyecto, seccion "Como cortar de verdad").

Revision ID: 4d623f7a3ab9
Revises:
Create Date: 2026-09-29 02:06:41.721648

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4d623f7a3ab9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Crea el esquema completo, tal como esta hoy. Seguro en una base vacia:
    usa IF NOT EXISTS en todos lados, igual que init_db()."""
    op.execute("""
        CREATE TABLE IF NOT EXISTS users (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            username TEXT NOT NULL UNIQUE,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            email TEXT,
            password_hash TEXT,
            email_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
            confirmation_token TEXT,
            confirmation_expires TIMESTAMPTZ,
            membership_plan TEXT,
            membership_status TEXT NOT NULL DEFAULT 'inactive',
            membership_started_at TIMESTAMPTZ,
            membership_expires_at TIMESTAMPTZ,
            reset_token_hash TEXT,
            reset_expires TIMESTAMPTZ,
            is_active BOOLEAN NOT NULL DEFAULT TRUE
        )
    """)
    op.execute("""
        CREATE TABLE IF NOT EXISTS service_records (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id BIGINT NOT NULL REFERENCES users(id),
            job TEXT NOT NULL,
            payment DOUBLE PRECISION NOT NULL DEFAULT 0,
            service_history TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'pendiente',
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
    """)
    op.execute("""
        CREATE TABLE IF NOT EXISTS membership_payments (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            payment_reference TEXT NOT NULL UNIQUE,
            user_id BIGINT NOT NULL REFERENCES users(id),
            plan TEXT NOT NULL,
            amount DOUBLE PRECISION NOT NULL,
            preference_id TEXT,
            mp_payment_id TEXT UNIQUE,
            status TEXT NOT NULL DEFAULT 'pending',
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            paid_at TIMESTAMPTZ
        )
    """)
    op.execute("""
        CREATE TABLE IF NOT EXISTS contact_messages (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT NOT NULL,
            email TEXT NOT NULL,
            phone TEXT,
            message TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'new',
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
    """)
    op.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS users_email_unique "
        "ON users(LOWER(email)) WHERE email IS NOT NULL"
    )
    op.execute("CREATE UNIQUE INDEX IF NOT EXISTS users_username_unique ON users(LOWER(username))")
    op.execute("CREATE INDEX IF NOT EXISTS membership_payments_user_id_idx ON membership_payments(user_id)")
    op.execute("CREATE INDEX IF NOT EXISTS service_records_user_id_idx ON service_records(user_id)")
    for table in ("users", "service_records", "membership_payments", "contact_messages"):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")


def downgrade() -> None:
    """Destructivo: borra las 4 tablas y todo lo que tengan cargado. No se usa
    en produccion; queda solo por si hace falta recrear una base de pruebas."""
    op.execute("DROP TABLE IF EXISTS membership_payments")
    op.execute("DROP TABLE IF EXISTS service_records")
    op.execute("DROP TABLE IF EXISTS contact_messages")
    op.execute("DROP TABLE IF EXISTS users")
